from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace

import pytest
from psd_tools import PSDImage

from app.core.slice_parser import (
    MalformedSliceResourceError,
    UnsupportedSliceVersionError,
    parse_document_slices,
    parse_slice_resource,
)
from app.models.slice_info import SliceInfo


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = json.loads(
    (PROJECT_ROOT / "tests" / "fixtures" / "baseline_manifest.json").read_text(
        encoding="utf-8"
    )
)


@dataclass
class FakeEnum:
    enum: bytes


def fixture_path(sample_name: str) -> Path:
    sample = MANIFEST[sample_name]
    environment_variable = sample["environment_variable"]
    value = os.environ.get(environment_variable)
    if not value:
        pytest.skip(f"{environment_variable} is not set")
    path = Path(value)
    if not path.is_file():
        pytest.fail(f"{environment_variable} does not point to a file: {path}")
    return path


def expected_full_width_bounds(sample_name: str) -> list[tuple[int, int, int, int]]:
    top = 0
    result = []
    for _, width, height, _, _ in MANIFEST[sample_name]["outputs"]:
        bottom = top + height
        result.append((0, top, width, bottom))
        top = bottom
    return result


def descriptor_slice(
    *,
    slice_id: int,
    bounds: tuple[int, int, int, int],
    origin: bytes | None,
    name: str = "",
    string_keys: bool = False,
) -> dict[object, object]:
    left, top, right, bottom = bounds
    keys = {
        "slice_id": "sliceID" if string_keys else b"sliceID",
        "bounds": "bounds" if string_keys else b"bounds",
        "left": "Left" if string_keys else b"Left",
        "top": "Top " if string_keys else b"Top ",
        "right": "Rght" if string_keys else b"Rght",
        "bottom": "Btom" if string_keys else b"Btom",
        "origin": "origin" if string_keys else b"origin",
        "type": "Type" if string_keys else b"Type",
        "name": "name" if string_keys else b"name",
    }
    record: dict[object, object] = {
        keys["slice_id"]: slice_id,
        keys["bounds"]: {
            keys["left"]: left,
            keys["top"]: top,
            keys["right"]: right,
            keys["bottom"]: bottom,
        },
        keys["type"]: FakeEnum(b"Img "),
        keys["name"]: name,
    }
    if origin is not None:
        record[keys["origin"]] = FakeEnum(origin)
    return record


def descriptor_resource(
    version: int, records: list[dict[object, object]], *, string_keys: bool = False
) -> SimpleNamespace:
    key: str | bytes = "slices" if string_keys else b"slices"
    return SimpleNamespace(version=version, data={key: records})


def test_slice_info_calculated_properties() -> None:
    item = SliceInfo(
        index=3,
        slice_id=9,
        name="中文切片",
        left=10,
        top=20,
        right=110,
        bottom=220,
        is_automatic=False,
        source_version="V8",
    )
    assert item.width == 100
    assert item.height == 200
    assert item.bounds == (10, 20, 110, 220)
    assert item.covers_canvas(110, 220) is False


@pytest.mark.parametrize(
    ("sample_name", "expected_version"),
    [("psd_v8", "V8"), ("psb_v6", "V6")],
)
def test_real_fixture_bounds_match_legacy_baseline(
    sample_name: str, expected_version: str
) -> None:
    psd = PSDImage.open(fixture_path(sample_name))
    result = parse_document_slices(psd)

    assert result.source_version == expected_version
    assert len(result.all_slices) == 15
    assert len(result.exportable_slices) == 14
    assert len(result.excluded_slices) == 1
    assert result.excluded_slices[0].is_automatic
    assert [item.bounds for item in result.exportable_slices] == (
        expected_full_width_bounds(sample_name)
    )
    assert not result.has_errors


@pytest.mark.parametrize("version", [7, 8])
def test_descriptor_versions_use_the_same_normalized_model(version: int) -> None:
    resource = descriptor_resource(
        version,
        [
            descriptor_slice(
                slice_id=0,
                bounds=(0, 0, 1440, 2000),
                origin=b"autoGenerated",
            ),
            descriptor_slice(
                slice_id=2,
                bounds=(0, 0, 1440, 800),
                origin=b"userGenerated",
                name="顶部",
            ),
            descriptor_slice(
                slice_id=1,
                bounds=(0, 800, 1440, 2000),
                origin=b"userGenerated",
                name="底部",
            ),
        ],
    )

    result = parse_slice_resource(
        resource, canvas_width=1440, canvas_height=2000
    )

    assert result.source_version == f"V{version}"
    assert [item.slice_id for item in result.exportable_slices] == [2, 1]
    assert [item.name for item in result.exportable_slices] == ["顶部", "底部"]
    assert len(result.excluded_slices) == 1
    assert result.excluded_slices[0].is_automatic


def test_descriptor_accepts_string_keys() -> None:
    record = descriptor_slice(
        slice_id=7,
        bounds=(10, 20, 110, 220),
        origin=b"userGenerated",
        name="中文名称",
        string_keys=True,
    )
    resource = descriptor_resource(7, [record], string_keys=True)

    result = parse_slice_resource(resource, canvas_width=200, canvas_height=300)

    assert result.exportable_slices[0].bounds == (10, 20, 110, 220)
    assert result.exportable_slices[0].name == "中文名称"


def test_user_generated_full_canvas_slice_is_kept() -> None:
    resource = descriptor_resource(
        8,
        [
            descriptor_slice(
                slice_id=1,
                bounds=(0, 0, 100, 200),
                origin=b"userGenerated",
            ),
            descriptor_slice(
                slice_id=2,
                bounds=(0, 0, 100, 100),
                origin=b"userGenerated",
            ),
        ],
    )
    result = parse_slice_resource(resource, canvas_width=100, canvas_height=200)

    assert len(result.exportable_slices) == 2
    assert not result.issues


@pytest.mark.parametrize("origin", [None, b"futureGenerated"])
def test_unknown_full_canvas_slice_is_kept_with_warning(
    origin: bytes | None,
) -> None:
    resource = descriptor_resource(
        8,
        [
            descriptor_slice(
                slice_id=1,
                bounds=(0, 0, 100, 200),
                origin=origin,
            )
        ],
    )
    result = parse_slice_resource(resource, canvas_width=100, canvas_height=200)

    assert len(result.exportable_slices) == 1
    assert "ambiguous_full_canvas" in {issue.code for issue in result.issues}


def test_only_automatic_slice_produces_no_exportable_slices() -> None:
    resource = descriptor_resource(
        8,
        [
            descriptor_slice(
                slice_id=0,
                bounds=(0, 0, 100, 200),
                origin=b"autoGenerated",
            )
        ],
    )
    result = parse_slice_resource(resource, canvas_width=100, canvas_height=200)

    assert not result.exportable_slices
    assert "only_automatic_slices" in {issue.code for issue in result.issues}


def test_sorting_uses_top_left_then_original_index() -> None:
    resource = descriptor_resource(
        8,
        [
            descriptor_slice(
                slice_id=30,
                bounds=(50, 100, 100, 150),
                origin=b"userGenerated",
            ),
            descriptor_slice(
                slice_id=10,
                bounds=(0, 100, 50, 150),
                origin=b"userGenerated",
            ),
            descriptor_slice(
                slice_id=20,
                bounds=(0, 100, 50, 150),
                origin=b"userGenerated",
            ),
        ],
    )
    result = parse_slice_resource(resource, canvas_width=100, canvas_height=200)

    assert [item.slice_id for item in result.exportable_slices] == [10, 20, 30]
    assert "duplicate_bounds" in {issue.code for issue in result.issues}


@pytest.mark.parametrize(
    ("bounds", "issue_code"),
    [
        ((10, 20, 10, 100), "non_positive_size"),
        ((0, 0, 101, 100), "out_of_canvas"),
    ],
)
def test_invalid_bounds_are_excluded_with_structured_issue(
    bounds: tuple[int, int, int, int], issue_code: str
) -> None:
    resource = descriptor_resource(
        8,
        [
            descriptor_slice(
                slice_id=1,
                bounds=bounds,
                origin=b"userGenerated",
            )
        ],
    )
    result = parse_slice_resource(resource, canvas_width=100, canvas_height=100)

    assert not result.exportable_slices
    assert result.excluded_slices[0].slice_id == 1
    assert issue_code in {issue.code for issue in result.issues}
    assert result.has_errors


def test_malformed_and_unsupported_resources_raise_typed_errors() -> None:
    with pytest.raises(UnsupportedSliceVersionError):
        parse_slice_resource(
            SimpleNamespace(version=5, data={}),
            canvas_width=100,
            canvas_height=100,
        )

    with pytest.raises(MalformedSliceResourceError):
        parse_slice_resource(
            SimpleNamespace(version=8, data={}),
            canvas_width=100,
            canvas_height=100,
        )
