from __future__ import annotations

from collections import Counter
from collections.abc import Iterable, Sequence
from typing import Any

from psd_tools.constants import Resource

from app.models.slice_info import SliceInfo, SliceIssue, SliceParseResult


class SliceParserError(ValueError):
    """Base class for user-facing slice parser errors."""


class SliceResourceMissingError(SliceParserError):
    """Raised when the document has no Photoshop slice resource."""


class UnsupportedSliceVersionError(SliceParserError):
    """Raised when the slice resource version is not V6, V7, or V8."""


class MalformedSliceResourceError(SliceParserError):
    """Raised when required slice data cannot be read."""


_V6_ORIGINS = {
    0: "autoGenerated",
    1: "layerGenerated",
    2: "userGenerated",
}


def _mapping_value(mapping: Any, key: str) -> Any:
    candidates: tuple[str | bytes, ...] = (key, key.encode("ascii"))
    for candidate in candidates:
        try:
            return mapping[candidate]
        except (KeyError, TypeError):
            continue
    raise KeyError(key)


def _optional_mapping_value(mapping: Any, *keys: str) -> Any | None:
    for key in keys:
        try:
            return _mapping_value(mapping, key)
        except KeyError:
            continue
    return None


def _normalized_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        try:
            value = value.decode("utf-8")
        except UnicodeDecodeError:
            value = value.decode("latin-1")
    return str(value).strip().strip("\x00")


def _normalized_enum(value: Any) -> str | int | None:
    if value is None:
        return None
    enum_value = getattr(value, "enum", value)
    if isinstance(enum_value, int):
        return enum_value
    text = _normalized_text(enum_value)
    return text or None


def _is_automatic_origin(origin: str | int | None) -> bool:
    if not isinstance(origin, str):
        return False
    compact = origin.replace("_", "").replace(" ", "").casefold()
    return compact in {"autogenerated", "automatic"}


def _is_known_origin(origin: str | int | None) -> bool:
    if not isinstance(origin, str):
        return False
    compact = origin.replace("_", "").replace(" ", "").casefold()
    return compact in {
        "autogenerated",
        "automatic",
        "layergenerated",
        "usergenerated",
    }


def _parse_v6(data: Any) -> list[SliceInfo]:
    records = getattr(data, "items", None)
    if records is None or callable(records):
        raise MalformedSliceResourceError(
            "V6 slice resource does not contain an item list."
        )

    slices: list[SliceInfo] = []
    for index, record in enumerate(records):
        try:
            left, top, right, bottom = map(int, record.bbox)
        except (AttributeError, TypeError, ValueError) as error:
            raise MalformedSliceResourceError(
                f"V6 slice {index} has invalid bounds."
            ) from error

        raw_origin = getattr(record, "origin", None)
        origin = _V6_ORIGINS.get(raw_origin, raw_origin)
        raw_slice_id = getattr(record, "slice_id", None)
        slice_id = int(raw_slice_id) if raw_slice_id is not None else None
        slices.append(
            SliceInfo(
                index=index,
                slice_id=slice_id,
                name=_normalized_text(getattr(record, "name", "")),
                left=left,
                top=top,
                right=right,
                bottom=bottom,
                is_automatic=_is_automatic_origin(origin),
                source_version="V6",
                origin=origin,
                slice_type=getattr(record, "slice_type", None),
            )
        )
    return slices


def _descriptor_records(data: Any) -> Sequence[Any]:
    try:
        records = _mapping_value(data, "slices")
    except KeyError as error:
        raise MalformedSliceResourceError(
            "V7/V8 slice resource does not contain a slices list."
        ) from error
    if isinstance(records, (str, bytes)) or not isinstance(records, Iterable):
        raise MalformedSliceResourceError(
            "V7/V8 slice resource contains an invalid slices list."
        )
    return tuple(records)


def _parse_descriptor(data: Any, version: int) -> list[SliceInfo]:
    slices: list[SliceInfo] = []
    for index, record in enumerate(_descriptor_records(data)):
        try:
            bounds = _mapping_value(record, "bounds")
            left = int(_mapping_value(bounds, "Left"))
            top = int(_mapping_value(bounds, "Top "))
            right = int(_mapping_value(bounds, "Rght"))
            bottom = int(_mapping_value(bounds, "Btom"))
        except (KeyError, TypeError, ValueError) as error:
            raise MalformedSliceResourceError(
                f"V{version} slice {index} has invalid bounds."
            ) from error

        raw_slice_id = _optional_mapping_value(record, "sliceID")
        slice_id = int(raw_slice_id) if raw_slice_id is not None else None
        origin = _normalized_enum(_optional_mapping_value(record, "origin"))
        slice_type = _normalized_enum(
            _optional_mapping_value(record, "Type", "sliceType")
        )
        name = _normalized_text(
            _optional_mapping_value(record, "Nm  ", "name", "null")
        )
        slices.append(
            SliceInfo(
                index=index,
                slice_id=slice_id,
                name=name,
                left=left,
                top=top,
                right=right,
                bottom=bottom,
                is_automatic=_is_automatic_origin(origin),
                source_version=f"V{version}",
                origin=origin,
                slice_type=slice_type,
            )
        )
    return slices


def _normalize_slices(
    slices: Sequence[SliceInfo],
    *,
    source_version: str,
    canvas_width: int,
    canvas_height: int,
) -> SliceParseResult:
    if canvas_width <= 0 or canvas_height <= 0:
        raise ValueError("Canvas dimensions must be positive.")

    exportable: list[SliceInfo] = []
    excluded: list[SliceInfo] = []
    issues: list[SliceIssue] = []
    duplicate_counts = Counter(item.bounds for item in slices)

    for item in slices:
        if item.width <= 0 or item.height <= 0:
            excluded.append(item)
            issues.append(
                SliceIssue(
                    code="non_positive_size",
                    message=(
                        f"Slice {item.index} has a non-positive size: "
                        f"{item.width} x {item.height}."
                    ),
                    severity="error",
                    slice_index=item.index,
                    slice_id=item.slice_id,
                )
            )
            continue

        if not (
            0 <= item.left < item.right <= canvas_width
            and 0 <= item.top < item.bottom <= canvas_height
        ):
            excluded.append(item)
            issues.append(
                SliceIssue(
                    code="out_of_canvas",
                    message=(
                        f"Slice {item.index} is outside the "
                        f"{canvas_width} x {canvas_height} canvas."
                    ),
                    severity="error",
                    slice_index=item.index,
                    slice_id=item.slice_id,
                )
            )
            continue

        if item.is_automatic:
            excluded.append(item)
            continue

        if item.covers_canvas(
            canvas_width, canvas_height
        ) and not _is_known_origin(item.origin):
            issues.append(
                SliceIssue(
                    code="ambiguous_full_canvas",
                    message=(
                        f"Slice {item.index} covers the full canvas but its "
                        "origin is missing or unknown; it was kept for user "
                        "review."
                    ),
                    slice_index=item.index,
                    slice_id=item.slice_id,
                )
            )

        if duplicate_counts[item.bounds] > 1:
            issues.append(
                SliceIssue(
                    code="duplicate_bounds",
                    message=(
                        f"Slice {item.index} has the same bounds as another "
                        "slice and was kept."
                    ),
                    slice_index=item.index,
                    slice_id=item.slice_id,
                )
            )

        exportable.append(item)

    if slices and not exportable and all(item.is_automatic for item in slices):
        issues.append(
            SliceIssue(
                code="only_automatic_slices",
                message="The document contains only automatic Photoshop slices.",
            )
        )
    elif not slices:
        issues.append(
            SliceIssue(
                code="no_slices",
                message="The Photoshop slice resource contains no slices.",
            )
        )

    exportable.sort(key=lambda item: (item.top, item.left, item.index))
    return SliceParseResult(
        source_version=source_version,
        all_slices=tuple(slices),
        exportable_slices=tuple(exportable),
        excluded_slices=tuple(excluded),
        issues=tuple(issues),
    )


def parse_slice_resource(
    slice_resource: Any,
    *,
    canvas_width: int,
    canvas_height: int,
) -> SliceParseResult:
    """Parse and normalize one psd-tools Slices resource."""

    version = int(getattr(slice_resource, "version", 0))
    data = getattr(slice_resource, "data", None)
    if version == 6:
        slices = _parse_v6(data)
    elif version in (7, 8):
        slices = _parse_descriptor(data, version)
    else:
        raise UnsupportedSliceVersionError(
            f"Unsupported Photoshop slice resource version: {version}."
        )

    return _normalize_slices(
        slices,
        source_version=f"V{version}",
        canvas_width=canvas_width,
        canvas_height=canvas_height,
    )


def parse_document_slices(psd: Any) -> SliceParseResult:
    """Read and normalize the slice resource from a PSDImage-like object."""

    slice_resource = psd.image_resources.get_data(Resource.SLICES)
    if slice_resource is None:
        raise SliceResourceMissingError(
            "The PSD/PSB does not contain a Photoshop slice resource."
        )
    return parse_slice_resource(
        slice_resource,
        canvas_width=int(psd.width),
        canvas_height=int(psd.height),
    )
